# Generated by Django 4.0.1 on 2022-01-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_actor_movie_actor_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor_movie',
            name='age',
        ),
    ]
